apiVersion: v1
kind: Service
metadata:
  name: ${var.app_name}-service
  namespace: ${var.app_namespace}
spec:
  type: NodePort  # Cheaper than LoadBalancer
  selector:
    app: ${var.app_name}
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30080